[package]
name = "wasm_js_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wizer = "1.4.0"
binaryen = "0.12.1"
stdio-override = "0.1.3"